/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>
#include <glade/glade-xml.h>
#include <stdlib.h>

#include "gprof-profile-data.h"
#include "gprof-view-manager.h"
#include "gprof-flat-profile-view.h"
#include "gprof-call-graph-view.h"
#include "gprof-function-call-tree-view.h"
#include "gprof-function-call-chart-view.h"



static void 
on_main_window_delete_event (GtkWidget *widget, GdkEvent * event,
							 gpointer *user_data)
{
	gtk_widget_destroy (widget);
	gtk_main_quit ();
}

static GtkWidget *
create_main_window (GladeXML *glade)
{
	GtkWidget *window;
	
	window = glade_xml_get_widget (glade, "main_window");
	
	g_signal_connect (window, "delete-event", 
					  G_CALLBACK(on_main_window_delete_event), NULL);
	
	return window;
}

int
main (int argc, char *argv[])
{
    GladeXML *main_ui;
	GtkWidget *main_window;
	GProfViewManager *manager;
	GProfProfileData *data;

  gnome_program_init (PACKAGE, VERSION, LIBGNOMEUI_MODULE,
                      argc, argv,
                      GNOME_PARAM_APP_DATADIR, PACKAGE_DATA_DIR,
                      NULL);
	
	main_ui = glade_xml_new (PACKAGE_DATA_DIR
							 "/profileparser-gui/profileparser-gui.glade",  
							 NULL, NULL);
	main_window = create_main_window (main_ui);
	
	manager = gprof_view_manager_new ();
	gtk_widget_show (main_window);
	gtk_widget_show (gprof_view_manager_get_notebook (manager));
	
	data = gprof_profile_data_new ();
	gprof_view_manager_add_view (manager, 
								GPROF_VIEW (gprof_flat_profile_view_new (data)), 
								"Flat Profile");
	gprof_view_manager_add_view (manager, 
								GPROF_VIEW (gprof_call_graph_view_new (data)), 
								"Call Graph");
	gprof_view_manager_add_view (manager, 
								GPROF_VIEW (gprof_function_call_tree_view_new (data)), 
								"Function Call Tree");
	gprof_view_manager_add_view (manager,
								 GPROF_VIEW (gprof_function_call_chart_view_new (data)),
								 "Function Call Chart");
	g_object_unref (main_ui);
	
	gtk_container_add (GTK_CONTAINER (main_window), 
					   gprof_view_manager_get_notebook (manager)); 
	
	gprof_profile_data_init_profile (data, argv[1]);
	gprof_view_manager_refresh_views (manager);

  gtk_main ();
  
  gprof_view_manager_free (manager);
  gprof_profile_data_free (data);
  return 0;
}
