## Lexers make file
LEXER_OBJS = \
	$(top_srcdir)/plugins/editor/scintilla/StyleContext.o\
	$(top_srcdir)/plugins/editor/scintilla/LexAda.o\
	$(top_srcdir)/plugins/editor/scintilla/LexAPDL.o\
	$(top_srcdir)/plugins/editor/scintilla/LexAsm.o\
	$(top_srcdir)/plugins/editor/scintilla/LexAsn1.o\
	$(top_srcdir)/plugins/editor/scintilla/LexAU3.o\
	$(top_srcdir)/plugins/editor/scintilla/LexAVE.o\
	$(top_srcdir)/plugins/editor/scintilla/LexBaan.o\
	$(top_srcdir)/plugins/editor/scintilla/LexBash.o\
	$(top_srcdir)/plugins/editor/scintilla/LexBasic.o\
	$(top_srcdir)/plugins/editor/scintilla/LexBullant.o\
	$(top_srcdir)/plugins/editor/scintilla/LexCaml.o\
	$(top_srcdir)/plugins/editor/scintilla/LexCLW.o\
	$(top_srcdir)/plugins/editor/scintilla/LexConf.o\
	$(top_srcdir)/plugins/editor/scintilla/LexCPP.o\
	$(top_srcdir)/plugins/editor/scintilla/LexCrontab.o\
	$(top_srcdir)/plugins/editor/scintilla/LexCsound.o\
	$(top_srcdir)/plugins/editor/scintilla/LexCSS.o\
	$(top_srcdir)/plugins/editor/scintilla/LexEiffel.o\
	$(top_srcdir)/plugins/editor/scintilla/LexErlang.o\
	$(top_srcdir)/plugins/editor/scintilla/LexEScript.o\
	$(top_srcdir)/plugins/editor/scintilla/LexFlagship.o\
	$(top_srcdir)/plugins/editor/scintilla/LexForth.o\
	$(top_srcdir)/plugins/editor/scintilla/LexFortran.o\
	$(top_srcdir)/plugins/editor/scintilla/LexGui4Cli.o\
	$(top_srcdir)/plugins/editor/scintilla/LexHaskell.o\
	$(top_srcdir)/plugins/editor/scintilla/LexHTML.o\
	$(top_srcdir)/plugins/editor/scintilla/LexInno.o\
	$(top_srcdir)/plugins/editor/scintilla/LexKix.o\
	$(top_srcdir)/plugins/editor/scintilla/LexLisp.o\
	$(top_srcdir)/plugins/editor/scintilla/LexLout.o\
	$(top_srcdir)/plugins/editor/scintilla/LexLua.o\
	$(top_srcdir)/plugins/editor/scintilla/LexMatlab.o\
	$(top_srcdir)/plugins/editor/scintilla/LexMetapost.o\
	$(top_srcdir)/plugins/editor/scintilla/LexMMIXAL.o\
	$(top_srcdir)/plugins/editor/scintilla/LexMPT.o\
	$(top_srcdir)/plugins/editor/scintilla/LexMSSQL.o\
	$(top_srcdir)/plugins/editor/scintilla/LexNsis.o\
	$(top_srcdir)/plugins/editor/scintilla/LexOpal.o\
	$(top_srcdir)/plugins/editor/scintilla/LexOthers.o\
	$(top_srcdir)/plugins/editor/scintilla/LexPascal.o\
	$(top_srcdir)/plugins/editor/scintilla/LexPB.o\
	$(top_srcdir)/plugins/editor/scintilla/LexPerl.o\
	$(top_srcdir)/plugins/editor/scintilla/LexPOV.o\
	$(top_srcdir)/plugins/editor/scintilla/LexPS.o\
	$(top_srcdir)/plugins/editor/scintilla/LexPython.o\
	$(top_srcdir)/plugins/editor/scintilla/LexRebol.o\
	$(top_srcdir)/plugins/editor/scintilla/LexRuby.o\
	$(top_srcdir)/plugins/editor/scintilla/LexScriptol.o\
	$(top_srcdir)/plugins/editor/scintilla/LexSmalltalk.o\
	$(top_srcdir)/plugins/editor/scintilla/LexSpecman.o\
	$(top_srcdir)/plugins/editor/scintilla/LexSpice.o\
	$(top_srcdir)/plugins/editor/scintilla/LexSQL.o\
	$(top_srcdir)/plugins/editor/scintilla/LexTADS3.o\
	$(top_srcdir)/plugins/editor/scintilla/LexTCL.o\
	$(top_srcdir)/plugins/editor/scintilla/LexTeX.o\
	$(top_srcdir)/plugins/editor/scintilla/LexVB.o\
	$(top_srcdir)/plugins/editor/scintilla/LexVerilog.o\
	$(top_srcdir)/plugins/editor/scintilla/LexVHDL.o\
	$(top_srcdir)/plugins/editor/scintilla/LexYAML.o

LEXER_SRCS = \
	LexAda.cxx\
	LexAPDL.cxx\
	LexAsm.cxx\
	LexAsn1.cxx\
	LexAU3.cxx\
	LexAVE.cxx\
	LexBaan.cxx\
	LexBash.cxx\
	LexBasic.cxx\
	LexBullant.cxx\
	LexCaml.cxx\
	LexCLW.cxx\
	LexConf.cxx\
	LexCPP.cxx\
	LexCrontab.cxx\
	LexCsound.cxx\
	LexCSS.cxx\
	LexEiffel.cxx\
	LexErlang.cxx\
	LexEScript.cxx\
	LexFlagship.cxx\
	LexForth.cxx\
	LexFortran.cxx\
	LexGui4Cli.cxx\
	LexHaskell.cxx\
	LexHTML.cxx\
	LexInno.cxx\
	LexKix.cxx\
	LexLisp.cxx\
	LexLout.cxx\
	LexLua.cxx\
	LexMatlab.cxx\
	LexMetapost.cxx\
	LexMMIXAL.cxx\
	LexMPT.cxx\
	LexMSSQL.cxx\
	LexNsis.cxx\
	LexOpal.cxx\
	LexOthers.cxx\
	LexPascal.cxx\
	LexPB.cxx\
	LexPerl.cxx\
	LexPOV.cxx\
	LexPS.cxx\
	LexPython.cxx\
	LexRebol.cxx\
	LexRuby.cxx\
	LexScriptol.cxx\
	LexSmalltalk.cxx\
	LexSpecman.cxx\
	LexSpice.cxx\
	LexSQL.cxx\
	LexTADS3.cxx\
	LexTCL.cxx\
	LexTeX.cxx\
	LexVB.cxx\
	LexVerilog.cxx\
	LexVHDL.cxx\
	LexYAML.cxx
