.TH "Anjuta" "1" "0.1.10-pre" "Rob Bradford" ""
.SH "NAME"
.LP 
anjuta \- GNOME Integrated Development Environment
.SH "SYNTAX"
.LP 
anjuta [\fIoption\fP]
.SH "DESCRIPTION"
.LP 
Anjuta is a GNOME IDE and can be used to create either GNOME/GTK+ applications with glade or glade\-gnome, or can be used for creating generic applications. It is primarily designed for use with C/C++ and features an easy to use debugger and compilation environment.
.SH "OPTIONS"
.LP 
\fB\-\-help, \-h\fR
Output help information and exit.
.TP 
\fB\-\-version\fR
Output version information and exit.
.TP 
Anjuta supports all the generic GNOME and GTK options, a full list is available on the Anjuta help screen.
.SH "AUTHORS"
.LP 
This man page was written by Rob Bradford <robster@debian.org>. Anjuta was developed by Kh. Naba Kumar Singh <kh_naba@users.sourceforge.net>
.SH "SEE ALSO"
.LP 
anjuta_launcher(1)
