## Lexers make file
LEXER_OBJS = \
	$(top_srcdir)/scintilla/StyleContext.o\
	$(top_srcdir)/scintilla/LexAda.o\
	$(top_srcdir)/scintilla/LexAsm.o\
	$(top_srcdir)/scintilla/LexAVE.o\
	$(top_srcdir)/scintilla/LexBaan.o\
	$(top_srcdir)/scintilla/LexBullant.o\
	$(top_srcdir)/scintilla/LexCLW.o\
	$(top_srcdir)/scintilla/LexConf.o\
	$(top_srcdir)/scintilla/LexCPP.o\
	$(top_srcdir)/scintilla/LexCrontab.o\
	$(top_srcdir)/scintilla/LexCSS.o\
	$(top_srcdir)/scintilla/LexEiffel.o\
	$(top_srcdir)/scintilla/LexErlang.o\
	$(top_srcdir)/scintilla/LexEScript.o\
	$(top_srcdir)/scintilla/LexForth.o\
	$(top_srcdir)/scintilla/LexFortran.o\
	$(top_srcdir)/scintilla/LexHTML.o\
	$(top_srcdir)/scintilla/LexLisp.o\
	$(top_srcdir)/scintilla/LexLout.o\
	$(top_srcdir)/scintilla/LexLua.o\
	$(top_srcdir)/scintilla/LexMatlab.o\
	$(top_srcdir)/scintilla/LexMetapost.o\
	$(top_srcdir)/scintilla/LexMMIXAL.o\
	$(top_srcdir)/scintilla/LexMPT.o\
	$(top_srcdir)/scintilla/LexNsis.o\
	$(top_srcdir)/scintilla/LexOthers.o\
	$(top_srcdir)/scintilla/LexPascal.o\
	$(top_srcdir)/scintilla/LexPB.o\
	$(top_srcdir)/scintilla/LexPerl.o\
	$(top_srcdir)/scintilla/LexPOV.o\
	$(top_srcdir)/scintilla/LexPS.o\
	$(top_srcdir)/scintilla/LexPython.o\
	$(top_srcdir)/scintilla/LexRuby.o\
	$(top_srcdir)/scintilla/LexScriptol.o\
	$(top_srcdir)/scintilla/LexSQL.o\
	$(top_srcdir)/scintilla/LexTeX.o\
	$(top_srcdir)/scintilla/LexVB.o\
	$(top_srcdir)/scintilla/LexYAML.o

LEXER_SRCS = \
	LexAda.cxx\
	LexAsm.cxx\
	LexAVE.cxx\
	LexBaan.cxx\
	LexBullant.cxx\
	LexCLW.cxx\
	LexConf.cxx\
	LexCPP.cxx\
	LexCrontab.cxx\
	LexCSS.cxx\
	LexEiffel.cxx\
	LexErlang.cxx\
	LexEScript.cxx\
	LexForth.cxx\
	LexFortran.cxx\
	LexHTML.cxx\
	LexLisp.cxx\
	LexLout.cxx\
	LexLua.cxx\
	LexMatlab.cxx\
	LexMetapost.cxx\
	LexMMIXAL.cxx\
	LexMPT.cxx\
	LexNsis.cxx\
	LexOthers.cxx\
	LexPascal.cxx\
	LexPB.cxx\
	LexPerl.cxx\
	LexPOV.cxx\
	LexPS.cxx\
	LexPython.cxx\
	LexRuby.cxx\
	LexScriptol.cxx\
	LexSQL.cxx\
	LexTeX.cxx\
	LexVB.cxx\
	LexYAML.cxx
