## Lexers make file
LEXER_OBJS = \
	$(top_srcdir)/scintilla/StyleContext.o\
	$(top_srcdir)/scintilla/LexAda.o\
	$(top_srcdir)/scintilla/LexAPDL.o\
	$(top_srcdir)/scintilla/LexAsm.o\
	$(top_srcdir)/scintilla/LexAsn1.o\
	$(top_srcdir)/scintilla/LexAU3.o\
	$(top_srcdir)/scintilla/LexAVE.o\
	$(top_srcdir)/scintilla/LexBaan.o\
	$(top_srcdir)/scintilla/LexBash.o\
	$(top_srcdir)/scintilla/LexBasic.o\
	$(top_srcdir)/scintilla/LexBullant.o\
	$(top_srcdir)/scintilla/LexCaml.o\
	$(top_srcdir)/scintilla/LexCLW.o\
	$(top_srcdir)/scintilla/LexConf.o\
	$(top_srcdir)/scintilla/LexCPP.o\
	$(top_srcdir)/scintilla/LexCrontab.o\
	$(top_srcdir)/scintilla/LexCsound.o\
	$(top_srcdir)/scintilla/LexCSS.o\
	$(top_srcdir)/scintilla/LexEiffel.o\
	$(top_srcdir)/scintilla/LexErlang.o\
	$(top_srcdir)/scintilla/LexEScript.o\
	$(top_srcdir)/scintilla/LexFlagship.o\
	$(top_srcdir)/scintilla/LexForth.o\
	$(top_srcdir)/scintilla/LexFortran.o\
	$(top_srcdir)/scintilla/LexGui4Cli.o\
	$(top_srcdir)/scintilla/LexHaskell.o\
	$(top_srcdir)/scintilla/LexHTML.o\
	$(top_srcdir)/scintilla/LexInno.o\
	$(top_srcdir)/scintilla/LexKix.o\
	$(top_srcdir)/scintilla/LexLisp.o\
	$(top_srcdir)/scintilla/LexLout.o\
	$(top_srcdir)/scintilla/LexLua.o\
	$(top_srcdir)/scintilla/LexMatlab.o\
	$(top_srcdir)/scintilla/LexMetapost.o\
	$(top_srcdir)/scintilla/LexMMIXAL.o\
	$(top_srcdir)/scintilla/LexMPT.o\
	$(top_srcdir)/scintilla/LexMSSQL.o\
	$(top_srcdir)/scintilla/LexNsis.o\
	$(top_srcdir)/scintilla/LexOpal.o\
	$(top_srcdir)/scintilla/LexOthers.o\
	$(top_srcdir)/scintilla/LexPascal.o\
	$(top_srcdir)/scintilla/LexPB.o\
	$(top_srcdir)/scintilla/LexPerl.o\
	$(top_srcdir)/scintilla/LexPOV.o\
	$(top_srcdir)/scintilla/LexPS.o\
	$(top_srcdir)/scintilla/LexPython.o\
	$(top_srcdir)/scintilla/LexRebol.o\
	$(top_srcdir)/scintilla/LexRuby.o\
	$(top_srcdir)/scintilla/LexScriptol.o\
	$(top_srcdir)/scintilla/LexSmalltalk.o\
	$(top_srcdir)/scintilla/LexSpecman.o\
	$(top_srcdir)/scintilla/LexSQL.o\
	$(top_srcdir)/scintilla/LexTADS3.o\
	$(top_srcdir)/scintilla/LexTCL.o\
	$(top_srcdir)/scintilla/LexTeX.o\
	$(top_srcdir)/scintilla/LexVB.o\
	$(top_srcdir)/scintilla/LexVerilog.o\
	$(top_srcdir)/scintilla/LexVHDL.o\
	$(top_srcdir)/scintilla/LexYAML.o

LEXER_SRCS = \
	LexAda.cxx\
	LexAPDL.cxx\
	LexAsm.cxx\
	LexAsn1.cxx\
	LexAU3.cxx\
	LexAVE.cxx\
	LexBaan.cxx\
	LexBash.cxx\
	LexBasic.cxx\
	LexBullant.cxx\
	LexCaml.cxx\
	LexCLW.cxx\
	LexConf.cxx\
	LexCPP.cxx\
	LexCrontab.cxx\
	LexCsound.cxx\
	LexCSS.cxx\
	LexEiffel.cxx\
	LexErlang.cxx\
	LexEScript.cxx\
	LexFlagship.cxx\
	LexForth.cxx\
	LexFortran.cxx\
	LexGui4Cli.cxx\
	LexHaskell.cxx\
	LexHTML.cxx\
	LexInno.cxx\
	LexKix.cxx\
	LexLisp.cxx\
	LexLout.cxx\
	LexLua.cxx\
	LexMatlab.cxx\
	LexMetapost.cxx\
	LexMMIXAL.cxx\
	LexMPT.cxx\
	LexMSSQL.cxx\
	LexNsis.cxx\
	LexOpal.cxx\
	LexOthers.cxx\
	LexPascal.cxx\
	LexPB.cxx\
	LexPerl.cxx\
	LexPOV.cxx\
	LexPS.cxx\
	LexPython.cxx\
	LexRebol.cxx\
	LexRuby.cxx\
	LexScriptol.cxx\
	LexSmalltalk.cxx\
	LexSpecman.cxx\
	LexSQL.cxx\
	LexTADS3.cxx\
	LexTCL.cxx\
	LexTeX.cxx\
	LexVB.cxx\
	LexVerilog.cxx\
	LexVHDL.cxx\
	LexYAML.cxx
