/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/* FIXME: Move this out */
/* These actions will be segregated later into their respective plugins */
#include "anjuta-stock.h"

static EggActionGroupEntry menu_entries_file[] = {
  { "ActionMenuFile", N_("_File"), NULL, NULL, NULL, NULL, NULL },
  { "ActionMenuFileRecentProjects", N_("Recent Projec_ts"),  NULL, NULL, NULL, NULL, NULL },
  { "ActionExit", N_("_Quit"), GTK_STOCK_QUIT, "<control>q",
	N_("Quit Anjuta IDE"),
    G_CALLBACK (on_exit1_activate), NULL },
};

static EggActionGroupEntry menu_entries_navigation[] = {
  { "ActionMenuEditGoto", N_("G_oto"), NULL, NULL, NULL, NULL, NULL },
  { "ActionEditGotoMessagePrev", N_("_Previous message"),
	ANJUTA_STOCK_PREV_MESSAGE, "<control><alt>p",
	N_("Go to previous message"),
    G_CALLBACK (on_goto_prev_mesg1_activate), NULL },
  { "ActionEditGotoMessageNext", N_("_Next message"),
	ANJUTA_STOCK_NEXT_MESSAGE, "<control><alt>n",
	N_("Go to next message"),
    G_CALLBACK (on_goto_next_mesg1_activate), NULL },
  { "ActionEditGotoHistoryBack", N_("_Back"),
	GTK_STOCK_JUMP_TO, "<control><alt>b",
	N_("Go back"),
    G_CALLBACK (on_go_back_activate), NULL },
  { "ActionEditGotoHistoryForward", N_("_Forward"),
	GTK_STOCK_JUMP_TO, "<control><alt>f",
	N_("Go forward"),
    G_CALLBACK (on_go_forward_activate), NULL },
  { "ActionEditGotoTagDefinition", N_("_Tag definition"),
	GTK_STOCK_JUMP_TO, "<control>d",
	N_("Goto tag definition"),
    G_CALLBACK (on_goto_tag_activate), (gpointer) TRUE },
  { "ActionEditGotoTagDeclaration", N_("Tag _declaration"),
	GTK_STOCK_JUMP_TO, "<shift><control>d", N_("Goto tag declaration"),
    G_CALLBACK (on_goto_tag_activate), (gpointer) FALSE },
};

static EggActionGroupEntry menu_entries_edit[] = {
  { "ActionMenuEdit", N_("_Edit"), NULL, NULL, NULL, NULL, NULL },
};

static EggActionGroupEntry menu_entries_view[] = {
  { "ActionMenuView", N_("_View"), NULL, NULL, NULL, NULL, NULL },
  { "ActionMenuViewToolbars", N_("_Toolbars"), NULL, NULL, NULL, NULL, NULL },
  { "ActionViewToolbarMain", N_("_Main Toolbar"), NULL, NULL, NULL,
    G_CALLBACK (on_anjuta_toolbar_activate), ANJUTA_MAIN_TOOLBAR, TOGGLE_ACTION },
  { "ActionViewToolbarExtended", N_("_Extended Toolbar"), NULL, NULL, NULL,
    G_CALLBACK (on_anjuta_toolbar_activate), ANJUTA_EXTENDED_TOOLBAR, TOGGLE_ACTION },
  { "ActionViewToolbarDebug", N_("_Debug Toolbar"), NULL, NULL, NULL,
    G_CALLBACK (on_anjuta_toolbar_activate), ANJUTA_DEBUG_TOOLBAR, TOGGLE_ACTION },
  { "ActionViewToolbarBrowser", N_("_Browser Toolbar"), NULL, NULL, NULL,
    G_CALLBACK (on_anjuta_toolbar_activate), ANJUTA_BROWSER_TOOLBAR, TOGGLE_ACTION },
  { "ActionViewToolbarFormat", N_("_Format Toolbar"), NULL, NULL, NULL,
    G_CALLBACK (on_anjuta_toolbar_activate), ANJUTA_FORMAT_TOOLBAR, TOGGLE_ACTION },
  
  { "ActionViewWindowMessageManager", N_("Messages Window"),
	ANJUTA_STOCK_MESSAGES, "<control>F1",
	N_("Show/Hide the Message window"),
    G_CALLBACK (on_messages1_activate), NULL},
  { "ActionViewWindowProjectManager", N_("Project Window"),
	ANJUTA_STOCK_PROJECT, "<control>F2",
	N_("Show/Hide the Project window"),
    G_CALLBACK (on_project_listing1_activate), NULL},
  { "ActionViewWindowBookmarks", N_("B_ookmarks"), NULL, "<control>F3",
	N_("Show the Bookmark window"),
    G_CALLBACK (on_bookmarks1_activate), NULL},
  { "ActionViewWindowBreakpoints", N_("_Breakpoints"), NULL, "<control>F4",
	N_("Show breakpoints editor window"),
    G_CALLBACK (on_breakpoints1_activate), NULL},
  { "ActionViewWindowRegisters", N_("_Registers"), NULL, "<control>F6",
	N_("Show CPU registers and their contents"),
    G_CALLBACK (on_registers1_activate), NULL},
  { "ActionViewWindowSharedLibs", N_("Shared _Libraries"), NULL, "<control>F8",
	N_("Show shared libraries loaded by the program"),
    G_CALLBACK (on_shared_lib1_activate), NULL},
  { "ActionViewWindowKernelSignals", N_("_Kernel Signals"), NULL, "<control>F9",
	N_("Show the kernel signals editor window"),
    G_CALLBACK (on_kernal_signals1_activate), NULL},
  { "ActionViewWindowMemoryDump", N_("_Dump Window"), NULL, "<control>F10",
	N_("Show memory dump window"),
    G_CALLBACK (on_info_memory_activate), NULL},
/*  { "ActionViewWindowTerminal", N_("_Console"), NULL, "<control>F11",
	N_("Show the terminal"),
    G_CALLBACK (on_console1_activate), NULL},
  { "ActionViewWindowLocalVariables", N_("Show _Locals"), NULL, NULL,
	N_("Show/Hide Local variables in Message window"),
    G_CALLBACK (on_showhide_locals), NULL},*/
};

static EggActionGroupEntry menu_entries_project[] = {
  { "ActionMenuProject", N_("_Project"), NULL, NULL, NULL, NULL, NULL },
  { "ActionMenuProjectAddFile", N_("_Add file"), NULL, NULL, NULL, NULL, NULL },
  { "ActionProjectNew", N_("N_ew Project ..."), GTK_STOCK_NEW, NULL,
	N_("Create a Project using the Application Wizard"),
    G_CALLBACK (on_new_project1_activate), NULL },
  { "ActionProjectImport", N_("_Import Project ..."), GTK_STOCK_CONVERT, NULL,
	N_("Import an existing code project using the Project Import Wizard"),
    G_CALLBACK (on_import_project_activate), NULL },
  { "ActionProjectOpen", N_("Open P_roject ..."), ANJUTA_STOCK_OPEN_PROJECT, "<control>j",
	N_("Open a Project"),
    G_CALLBACK (on_open_project1_activate), NULL },
  { "ActionProjectSave", N_("Sa_ve Project"), ANJUTA_STOCK_SAVE_PROJECT, NULL,
	N_("Save the current Project"),
    G_CALLBACK (on_save_project1_activate), NULL },
  { "ActionProjectClose", N_("Close Pro_ject"), ANJUTA_STOCK_CLOSE_PROJECT, NULL,
	N_("Close the current Project"),
    G_CALLBACK (on_close_project1_activate), NULL },
  { "ActionProjectAddFileHearder", N_("_Include file"), NULL, NULL, NULL,
    G_CALLBACK (on_project_add_file1_activate),
	GINT_TO_POINTER(MODULE_INCLUDE + 1)},
  { "ActionProjectAddFileSource", N_("_Source file"), NULL, NULL, NULL,
    G_CALLBACK (on_project_add_file1_activate),
	GINT_TO_POINTER(MODULE_SOURCE + 1)},
  { "ActionProjectAddFileHelp", N_("_Help file"), NULL, NULL, NULL,
    G_CALLBACK (on_project_add_file1_activate),
	GINT_TO_POINTER(MODULE_HELP + 1)},
  { "ActionProjectAddFileData", N_("_Data file"), NULL, NULL, NULL,
    G_CALLBACK (on_project_add_file1_activate),
	GINT_TO_POINTER(MODULE_DATA + 1)},
  { "ActionProjectAddFilePixmap", N_("_Pixmap file"), NULL, NULL, NULL,
    G_CALLBACK (on_project_add_file1_activate),
	GINT_TO_POINTER(MODULE_PIXMAP + 1)},
  { "ActionProjectAddFileTranslation", N_("_Translation file"), NULL, NULL, NULL,
    G_CALLBACK (on_project_add_file1_activate),
	GINT_TO_POINTER(MODULE_PO + 1)},
  { "ActionProjectAddFileDoc", N_("D_oc file"), NULL, NULL, NULL,
    G_CALLBACK (on_project_add_file1_activate),
	GINT_TO_POINTER(MODULE_DOC + 1)},
  { "ActionProjectOpenInDefaultViewer", N_("Open in default _viewer"),
	GTK_STOCK_OPEN, NULL, NULL,
    G_CALLBACK (on_project_view1_activate), NULL},
  { "ActionProjectOpenInAnjuta", N_("_Open in Anjuta"),
	GTK_STOCK_OPEN, NULL, NULL,
    G_CALLBACK (on_project_edit1_activate), NULL},
  { "ActionProjectRemoveFile", N_("_Remove File"), GTK_STOCK_CLOSE, NULL, NULL,
    G_CALLBACK (on_project_remove1_activate), NULL},
  { "ActionProjectConfigure", N_("_Configure Project"),
	GTK_STOCK_PREFERENCES, NULL,
	N_("Configure options for the current Project"),
    G_CALLBACK (on_project_configure1_activate), NULL},
  { "ActionProjectInfo", N_("Project _Info"), GTK_STOCK_PROPERTIES, NULL,
	N_("Display the Project information"),
    G_CALLBACK (on_project_project_info1_activate), NULL},
/*  { "ActionProjectDock", N_("_Docked"), NULL, NULL,
	N_("Dock/Undock the Project Window"),
    G_CALLBACK (on_project_dock_undock1_activate), NULL, TOGGLE_ACTION},*/
  { "ActionProjectSymbolsUpdate", N_("_Update tags image"), NULL, NULL,
	N_("Update the tags image of the Project/opened files"),
    G_CALLBACK (on_update_tagmanager_activate), (gpointer) FALSE},
  { "ActionProjectSymbolsRebuild", N_("_Rebuild tags image"), NULL, NULL,
	N_("Rebuild the tags image of the Project"),
    G_CALLBACK (on_update_tagmanager_activate), (gpointer) TRUE},
  { "ActionProjectEditGUI", N_("Ed_it Application GUI ..."), NULL, "<alt>g",
	N_("Edit application GUI with the Glade GUI editor"),
    G_CALLBACK (on_edit_app_gui1_activate), NULL},
};

static EggActionGroupEntry menu_entries_build[] = {
  { "ActionMenuBuild", N_("_Build"), NULL, NULL, NULL, NULL, NULL },
  { "ActionBuildCompile", N_("_Compile"),
	ANJUTA_STOCK_COMPILE, "F9",
	N_("Compile the current source file"),
    G_CALLBACK (on_compile1_activate), NULL},
  { "ActionBuildCompileWithMake", N_("Compile With _Make"),
	ANJUTA_STOCK_COMPILE, "<shift>F9",
	N_("Compile the current source file using Make"),
    G_CALLBACK (on_make1_activate), NULL},
  { "ActionBuildBuild", N_("_Build"),
	ANJUTA_STOCK_BUILD, "F11",
	N_("Build the source directory of the Project or the current source file"),
    G_CALLBACK (on_build_project1_activate), NULL},
  { "ActionBuildBuildAll", N_("Build _All"),
	ANJUTA_STOCK_BUILD_ALL, "<shift>F11",
	N_("Build the whole Project"),
    G_CALLBACK (on_build_all_project1_activate), NULL},
  { "ActionBuildSave", N_("Save Build Messages"),
	NULL, NULL,
	N_("Save build messages to a file"),
    G_CALLBACK (on_save_build_messages_activate), NULL},
  { "ActionBuildInstall", N_("_Install"),
	NULL, NULL,
	N_("Install the Project on your system"),
    G_CALLBACK (on_install_project1_activate), NULL},
  { "ActionBuildDistribution", N_("Build _Distribution"),
	NULL, NULL,
	N_("Build the distribution tarball of the Project"),
    G_CALLBACK (on_build_dist_project1_activate), NULL},
  { "ActionBuildConfigure", N_("Con_figure ..."),
	ANJUTA_STOCK_CONFIGURE, NULL,
	N_("Configure the Project"),
    G_CALLBACK (on_configure_project1_activate), NULL},
  { "ActionBuildAutogen", N_("Auto _generate ..."),
	NULL, NULL,
	N_("Auto generate all the build files for the Project"),
    G_CALLBACK (on_autogen_project1_activate), NULL},
  { "ActionBuildClean", N_("Clea_n"),
	NULL, NULL,
	N_("Clean the source directory"),
    G_CALLBACK (on_clean_project1_activate), NULL},
  { "ActionBuildCleanAll", N_("Clean A_ll"),
	NULL, NULL,
	N_("Clean the whole Project directory"),
    G_CALLBACK (on_clean_all_project1_activate), NULL},
  { "ActionBuildStop", N_("_Stop Build"),
	GTK_STOCK_STOP, NULL,
	N_("Stop the current compile or build process"),
    G_CALLBACK (on_stop_build_make1_activate), NULL},
  { "ActionBuildExecute", N_("_Execute"),
	GTK_STOCK_EXECUTE, NULL,
	N_("Execute the program"),
    G_CALLBACK (on_go_execute1_activate), NULL},
  { "ActionBuildSetExecute", N_("Set _Program params ..."),
	GTK_STOCK_EXECUTE, NULL,
	N_("Set the execution parameters of the program"),
    G_CALLBACK (on_go_execute2_activate), NULL},
};


static EggActionGroupEntry menu_entries_settings[] = {
  { "ActionMenuSettings", N_("_Settings"), NULL, NULL, NULL, NULL, NULL },
  { "ActionSettingsBuild", N_("_Build Settings ..."),
	GTK_STOCK_PREFERENCES, NULL,
	N_("Settings for the compiler and linker"),
    G_CALLBACK (on_set_compiler1_activate), NULL},
  { "ActionSettingsPaths", N_("_Source Paths ..."),
	GTK_STOCK_PREFERENCES, NULL,
	N_("Specify the source paths for Anjuta to search"),
    G_CALLBACK (on_set_src_paths1_activate), NULL},
  { "ActionSettingsComamnds", N_("Co_mmands ..."),
	GTK_STOCK_PREFERENCES, NULL,
	N_("Specify the various commands for use"),
    G_CALLBACK (on_set_commands1_activate), NULL},
  { "ActionSettingsPreferences", N_("_Preferences ..."),
	GTK_STOCK_PROPERTIES, NULL,
	N_("Do you prefer coffee to tea? Check it out."),
    G_CALLBACK (on_set_preferences1_activate), NULL},
  { "ActionSettingseEditorColors", N_("_Editor colors and fonts ..."),
	GTK_STOCK_PROPERTIES, NULL,
	N_("Syntax highlighting settings"),
    G_CALLBACK (on_set_style_editor_activate), NULL},
  { "ActionSettingsFileFilters", N_("File view filters ..."),
	GTK_STOCK_PROPERTIES, NULL,
	N_("Edit file view filters"),
    G_CALLBACK (on_file_view_filters_activate), NULL},
  { "ActionSettingsUserProperties", N_("_Edit user.properties file ..."),
	GTK_STOCK_PROPERTIES, NULL,
	N_("Edit user properties file"),
    G_CALLBACK (on_edit_user_properties1_activate), NULL},
  { "ActionSettingsDefaults", N_("Set _Default Preferences"),
	GTK_STOCK_PROPERTIES, NULL,
	N_("But I prefer tea."),
    G_CALLBACK (on_set_default_preferences1_activate), NULL},
  { "ActionSettingsShortcuts", N_("C_ustomize shortcuts"),
	NULL, NULL,
	N_("Customize shortcuts associated with menu items"),
    G_CALLBACK (on_customize_shortcuts_activate), NULL},
  { "ActionSettingsTools", N_("_Tools Editor"),
	NULL, NULL,
	N_("Customize user-defined tools"),
    G_CALLBACK (on_tool_editor_activate), NULL},
  { "ActionSettingsStartwith", N_("St_art-with dialog"),
	NULL, NULL,
	N_("Show start-with dialog"),
    G_CALLBACK (on_start_with_dialog_activate), NULL},
  { "ActionSettingsSetup", N_("An_juta setup wizard"),
	NULL, NULL,
	N_("Setup wizard for first time run"),
    G_CALLBACK (on_setup_wizard_activate), NULL},
};

static EggActionGroupEntry menu_entries_help[] = {
  { "ActionMenuHelp", N_("_Help"), NULL, NULL, NULL, NULL, NULL },
  { "ActionHelpGnome", N_("The GNOME API pages"),
	GTK_STOCK_DIALOG_INFO, NULL,
	N_("Browse GNOME _API Pages"),
    G_CALLBACK (on_gnome_pages1_activate), NULL},
  { "ActionHelpMan", N_("Browse _Man Pages"),
	GTK_STOCK_DIALOG_INFO, NULL,
	N_("The good old manual pages"),
    G_CALLBACK (on_url_activate), "man:man"},
  { "ActionHelpInfo", N_("Browse _Info Pages"),
	GTK_STOCK_DIALOG_INFO, NULL,
	N_("The good info pages"),
    G_CALLBACK (on_url_activate), "info:info"},
  { "ActionHelpContext", N_("_Context Help"),
	GTK_STOCK_HELP, "<control>h",
	N_("Search help for the current word in the editor"),
    G_CALLBACK (on_context_help_activate), NULL},
  { "ActionHelpSearch", N_("_Search a topic"), GTK_STOCK_FIND, NULL,
	N_("May I help you?"),
    G_CALLBACK (on_search_a_topic1_activate), NULL},
  { "ActionHelpAnjutaHome", N_("Anjuta _Home Page"), GTK_STOCK_HOME, NULL,
	N_("Online documentation and resources"),
    G_CALLBACK (on_url_activate), "http://anjuta.org"},
  { "ActionHelpLidn", N_("_Libraries API references"), GTK_STOCK_JUMP_TO, NULL,
	N_("Online reference library for GDK, GLib, GNOME etc.."),
    G_CALLBACK (on_url_activate), "http://lidn.sourceforge.net"},
  { "ActionHelpBugReport", N_("Report _Bugs"), GTK_STOCK_JUMP_TO, NULL,
	N_("Submit a bug report for Anjuta"),
    G_CALLBACK (on_url_activate), "http://sourceforge.net/tracker/?atid=114222&group_id=14222&func=browse"},
  { "ActionHelpFeatureRequest", N_("Request _Features"),
	GTK_STOCK_JUMP_TO, NULL,
	N_("Submit a feature request for Anjuta"),
    G_CALLBACK (on_url_activate), "http://sourceforge.net/tracker/?atid=364222&group_id=14222&func=browse"},
  { "ActionHelpSubmitPatch", N_("Submit _patches"),
	GTK_STOCK_JUMP_TO, NULL,
	N_("Submit patches for Anjuta"),
    G_CALLBACK (on_url_activate), "http://sourceforge.net/tracker/?atid=314222&group_id=14222&func=browse"},
  { "ActionHelpFaq", N_("Ask a _question"),
	GTK_STOCK_JUMP_TO, NULL,
	N_("Submit a question for FAQs"),
    G_CALLBACK (on_url_activate), "mailto:anjuta-list@lists.sourceforge.net"},
  { "ActionAboutAnjuta", N_("_About"),
	GNOME_STOCK_ABOUT, NULL,
	N_("About Anjuta"),
    G_CALLBACK (on_about1_activate), NULL},
};
