/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "Gladen.h"

#if ( (TC_IMPL_TC_Gladen_GladeRef_0 == 'G') \
&& (TC_IMPL_TC_Gladen_GladeRef_1 == 'l') \
&& (TC_IMPL_TC_Gladen_GladeRef_2 == 'a') \
&& (TC_IMPL_TC_Gladen_GladeRef_3 == 'd') \
&& (TC_IMPL_TC_Gladen_GladeRef_4 == 'e') \
&& (TC_IMPL_TC_Gladen_GladeRef_5 == 'n') \
) && !defined(TC_DEF_TC_Gladen_GladeRef)
#define TC_DEF_TC_Gladen_GladeRef 1
const struct CORBA_TypeCode_struct TC_Gladen_GladeRef_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "GladeRef", "IDL:Gladen/GladeRef:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long Gladen_GladeRef__classid = 0;
