/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "Prj.h"

void
_ORBIT_skel_ProjectManager_PrjMan__get_srcLanguage(POA_ProjectManager_PrjMan *
						   _ORBIT_servant,
						   GIOPRecvBuffer *
						   _ORBIT_recv_buffer,
						   CORBA_Environment * ev,
						   CORBA_char *
						   (*_impl__get_srcLanguage)
						   (PortableServer_Servant
						    _servant,
						    CORBA_Environment * ev))
{
   CORBA_char *_ORBIT_retval;

   _ORBIT_retval = _impl__get_srcLanguage(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    register CORBA_unsigned_long _ORBIT_tmpvar_0;
	    CORBA_unsigned_long _ORBIT_tmpvar_1;

	    _ORBIT_tmpvar_1 = strlen(_ORBIT_retval) + 1;
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_1));
	       memcpy(_ORBIT_t, &(_ORBIT_tmpvar_1), sizeof(_ORBIT_tmpvar_1));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_tmpvar_1));
	    }
	    giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					   (_ORBIT_send_buffer),
					   (_ORBIT_retval),
					   sizeof(_ORBIT_retval
						  [_ORBIT_tmpvar_0]) *
					   _ORBIT_tmpvar_1);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      if (ev->_major == CORBA_NO_EXCEPTION)
	 CORBA_free(_ORBIT_retval);
   }
}
void
_ORBIT_skel_ProjectManager_PrjMan__get_projectName(POA_ProjectManager_PrjMan *
						   _ORBIT_servant,
						   GIOPRecvBuffer *
						   _ORBIT_recv_buffer,
						   CORBA_Environment * ev,
						   CORBA_char *
						   (*_impl__get_projectName)
						   (PortableServer_Servant
						    _servant,
						    CORBA_Environment * ev))
{
   CORBA_char *_ORBIT_retval;

   _ORBIT_retval = _impl__get_projectName(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    register CORBA_unsigned_long _ORBIT_tmpvar_0;
	    CORBA_unsigned_long _ORBIT_tmpvar_1;

	    _ORBIT_tmpvar_1 = strlen(_ORBIT_retval) + 1;
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_1));
	       memcpy(_ORBIT_t, &(_ORBIT_tmpvar_1), sizeof(_ORBIT_tmpvar_1));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_tmpvar_1));
	    }
	    giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					   (_ORBIT_send_buffer),
					   (_ORBIT_retval),
					   sizeof(_ORBIT_retval
						  [_ORBIT_tmpvar_0]) *
					   _ORBIT_tmpvar_1);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      if (ev->_major == CORBA_NO_EXCEPTION)
	 CORBA_free(_ORBIT_retval);
   }
}
void
_ORBIT_skel_ProjectManager_PrjMan_AddFileToProject(POA_ProjectManager_PrjMan *
						   _ORBIT_servant,
						   GIOPRecvBuffer *
						   _ORBIT_recv_buffer,
						   CORBA_Environment * ev,
						   CORBA_boolean
						   (*_impl_AddFileToProject)
						   (PortableServer_Servant
						    _servant,
						    const CORBA_char *
						    szCategory,
						    const CORBA_char *
						    szFileName,
						    CORBA_Environment * ev))
{
   CORBA_boolean _ORBIT_retval;
   CORBA_char *szCategory;
   CORBA_char *szFileName;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_4;
      CORBA_unsigned_long _ORBIT_tmpvar_5;
      register CORBA_unsigned_long _ORBIT_tmpvar_6;
      CORBA_unsigned_long _ORBIT_tmpvar_7;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_5))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 szCategory = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szCategory[_ORBIT_tmpvar_4]) * _ORBIT_tmpvar_5;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_7))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 szFileName = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szFileName[_ORBIT_tmpvar_6]) * _ORBIT_tmpvar_7;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_5 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 szCategory = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szCategory[_ORBIT_tmpvar_4]) * _ORBIT_tmpvar_5;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_7 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 szFileName = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szFileName[_ORBIT_tmpvar_6]) * _ORBIT_tmpvar_7;
      }
   }
   _ORBIT_retval =
      _impl_AddFileToProject(_ORBIT_servant, szCategory, szFileName, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_retval));
	       memcpy(_ORBIT_t, &(_ORBIT_retval), sizeof(_ORBIT_retval));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_retval));
	    }
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_ProjectManager_PrjMan_RemFileFromProject(POA_ProjectManager_PrjMan
						     * _ORBIT_servant,
						     GIOPRecvBuffer *
						     _ORBIT_recv_buffer,
						     CORBA_Environment * ev,
						     CORBA_boolean
						     (*_impl_RemFileFromProject)
						     (PortableServer_Servant
						      _servant,
						      const CORBA_char *
						      szCategory,
						      const CORBA_char *
						      szFileName,
						      CORBA_Environment * ev))
{
   CORBA_boolean _ORBIT_retval;
   CORBA_char *szCategory;
   CORBA_char *szFileName;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_4;
      CORBA_unsigned_long _ORBIT_tmpvar_5;
      register CORBA_unsigned_long _ORBIT_tmpvar_6;
      CORBA_unsigned_long _ORBIT_tmpvar_7;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_5))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 szCategory = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szCategory[_ORBIT_tmpvar_4]) * _ORBIT_tmpvar_5;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_7))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 szFileName = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szFileName[_ORBIT_tmpvar_6]) * _ORBIT_tmpvar_7;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_5 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 szCategory = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szCategory[_ORBIT_tmpvar_4]) * _ORBIT_tmpvar_5;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_7 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 szFileName = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szFileName[_ORBIT_tmpvar_6]) * _ORBIT_tmpvar_7;
      }
   }
   _ORBIT_retval =
      _impl_RemFileFromProject(_ORBIT_servant, szCategory, szFileName, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_retval));
	       memcpy(_ORBIT_t, &(_ORBIT_retval), sizeof(_ORBIT_retval));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_retval));
	    }
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_ProjectManager_PrjMan_SetClassInfo(POA_ProjectManager_PrjMan *
					       _ORBIT_servant,
					       GIOPRecvBuffer *
					       _ORBIT_recv_buffer,
					       CORBA_Environment * ev,
					       CORBA_boolean
					       (*_impl_SetClassInfo)
					       (PortableServer_Servant
						_servant,
						const CORBA_char * szClass,
						const CORBA_char * szFileDecl,
						const CORBA_char * szFileImpl,
						CORBA_Environment * ev))
{
   CORBA_boolean _ORBIT_retval;
   CORBA_char *szClass;
   CORBA_char *szFileDecl;
   CORBA_char *szFileImpl;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_6;
      CORBA_unsigned_long _ORBIT_tmpvar_7;
      register CORBA_unsigned_long _ORBIT_tmpvar_8;
      CORBA_unsigned_long _ORBIT_tmpvar_9;
      register CORBA_unsigned_long _ORBIT_tmpvar_10;
      CORBA_unsigned_long _ORBIT_tmpvar_11;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_7))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 szClass = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(szClass[_ORBIT_tmpvar_6]) * _ORBIT_tmpvar_7;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_9))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 szFileDecl = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szFileDecl[_ORBIT_tmpvar_8]) * _ORBIT_tmpvar_9;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_11))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 szFileImpl = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szFileImpl[_ORBIT_tmpvar_10]) * _ORBIT_tmpvar_11;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_7 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 szClass = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(szClass[_ORBIT_tmpvar_6]) * _ORBIT_tmpvar_7;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_9 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 szFileDecl = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szFileDecl[_ORBIT_tmpvar_8]) * _ORBIT_tmpvar_9;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_11 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 szFileImpl = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szFileImpl[_ORBIT_tmpvar_10]) * _ORBIT_tmpvar_11;
      }
   }
   _ORBIT_retval =
      _impl_SetClassInfo(_ORBIT_servant, szClass, szFileDecl, szFileImpl, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_retval));
	       memcpy(_ORBIT_t, &(_ORBIT_retval), sizeof(_ORBIT_retval));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_retval));
	    }
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_ProjectManager_PrjMan_SetGladeRef(POA_ProjectManager_PrjMan *
					      _ORBIT_servant,
					      GIOPRecvBuffer *
					      _ORBIT_recv_buffer,
					      CORBA_Environment * ev,
					      void (*_impl_SetGladeRef)
					      (PortableServer_Servant
					       _servant,
					       const CORBA_Object pgf,
					       CORBA_Environment * ev))
{
   CORBA_Object pgf;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = _ORBIT_curptr;
	 pgf =
	    ORBit_demarshal_object(_ORBIT_recv_buffer,
				   (((ORBit_ObjectKey *) _ORBIT_servant->
				     _private)->object->orb));
	 _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      } else {
	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = _ORBIT_curptr;
	 pgf =
	    ORBit_demarshal_object(_ORBIT_recv_buffer,
				   (((ORBit_ObjectKey *) _ORBIT_servant->
				     _private)->object->orb));
	 _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      }
   }
   _impl_SetGladeRef(_ORBIT_servant, pgf, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      CORBA_Object_release(pgf, ev);
   }
}
void
_ORBIT_skel_ProjectManager_PrjMan_SaveFileIfModified(POA_ProjectManager_PrjMan
						     * _ORBIT_servant,
						     GIOPRecvBuffer *
						     _ORBIT_recv_buffer,
						     CORBA_Environment * ev,
						     void
						     (*_impl_SaveFileIfModified)
						     (PortableServer_Servant
						      _servant,
						      const CORBA_char *
						      szFullPath,
						      CORBA_Environment * ev))
{
   CORBA_char *szFullPath;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 szFullPath = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szFullPath[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 szFullPath = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szFullPath[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_SaveFileIfModified(_ORBIT_servant, szFullPath, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_ProjectManager_PrjMan_ReloadFile(POA_ProjectManager_PrjMan *
					     _ORBIT_servant,
					     GIOPRecvBuffer *
					     _ORBIT_recv_buffer,
					     CORBA_Environment * ev,
					     void (*_impl_ReloadFile)
					     (PortableServer_Servant _servant,
					      const CORBA_char * szFullPath,
					      CORBA_Environment * ev))
{
   CORBA_char *szFullPath;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 szFullPath = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szFullPath[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 szFullPath = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(szFullPath[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_ReloadFile(_ORBIT_servant, szFullPath, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
static ORBitSkeleton
get_skel_ProjectManager_PrjMan(POA_ProjectManager_PrjMan * servant,
			       GIOPRecvBuffer * _ORBIT_recv_buffer,
			       gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'A':
	if (strcmp((opname + 1), "ddFileToProject"))
	   break;
	*impl =
	   (gpointer) servant->vepv->ProjectManager_PrjMan_epv->
	   AddFileToProject;
	return (ORBitSkeleton)
	   _ORBIT_skel_ProjectManager_PrjMan_AddFileToProject;
	break;
     case 'R':
	switch (opname[1]) {
	  case 'e':
	     switch (opname[2]) {
	       case 'l':
		  if (strcmp((opname + 3), "oadFile"))
		     break;
		  *impl =
		     (gpointer) servant->vepv->ProjectManager_PrjMan_epv->
		     ReloadFile;
		  return (ORBitSkeleton)
		     _ORBIT_skel_ProjectManager_PrjMan_ReloadFile;
		  break;
	       case 'm':
		  if (strcmp((opname + 3), "FileFromProject"))
		     break;
		  *impl =
		     (gpointer) servant->vepv->ProjectManager_PrjMan_epv->
		     RemFileFromProject;
		  return (ORBitSkeleton)
		     _ORBIT_skel_ProjectManager_PrjMan_RemFileFromProject;
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 'S':
	switch (opname[1]) {
	  case 'a':
	     if (strcmp((opname + 2), "veFileIfModified"))
		break;
	     *impl =
		(gpointer) servant->vepv->ProjectManager_PrjMan_epv->
		SaveFileIfModified;
	     return (ORBitSkeleton)
		_ORBIT_skel_ProjectManager_PrjMan_SaveFileIfModified;
	     break;
	  case 'e':
	     switch (opname[2]) {
	       case 't':
		  switch (opname[3]) {
		    case 'C':
		       if (strcmp((opname + 4), "lassInfo"))
			  break;
		       *impl =
			  (gpointer) servant->vepv->
			  ProjectManager_PrjMan_epv->SetClassInfo;
		       return (ORBitSkeleton)
			  _ORBIT_skel_ProjectManager_PrjMan_SetClassInfo;
		       break;
		    case 'G':
		       if (strcmp((opname + 4), "ladeRef"))
			  break;
		       *impl =
			  (gpointer) servant->vepv->
			  ProjectManager_PrjMan_epv->SetGladeRef;
		       return (ORBitSkeleton)
			  _ORBIT_skel_ProjectManager_PrjMan_SetGladeRef;
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case '_':
	switch (opname[1]) {
	  case 'g':
	     switch (opname[2]) {
	       case 'e':
		  switch (opname[3]) {
		    case 't':
		       switch (opname[4]) {
			 case '_':
			    switch (opname[5]) {
			      case 'p':
				 if (strcmp((opname + 6), "rojectName"))
				    break;
				 *impl =
				    (gpointer) servant->vepv->
				    ProjectManager_PrjMan_epv->
				    _get_projectName;
				 return (ORBitSkeleton)
				    _ORBIT_skel_ProjectManager_PrjMan__get_projectName;
				 break;
			      case 's':
				 if (strcmp((opname + 6), "rcLanguage"))
				    break;
				 *impl =
				    (gpointer) servant->vepv->
				    ProjectManager_PrjMan_epv->
				    _get_srcLanguage;
				 return (ORBitSkeleton)
				    _ORBIT_skel_ProjectManager_PrjMan__get_srcLanguage;
				 break;
			      default:
				 break;
			    }
			    break;
			 default:
			    break;
		       }
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_ProjectManager_PrjMan(CORBA_Object obj,
					POA_ProjectManager_PrjMan * servant)
{
   obj->vepv[ProjectManager_PrjMan__classid] =
      servant->vepv->ProjectManager_PrjMan_epv;
}

void
POA_ProjectManager_PrjMan__init(PortableServer_Servant servant,
				CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_ProjectManager_PrjMan,
"IDL:ProjectManager/PrjMan:1.0", (ORBit_local_objref_init) & init_local_objref_ProjectManager_PrjMan };
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!ProjectManager_PrjMan__classid)
      ProjectManager_PrjMan__classid = ORBit_register_class(&class_info);
}

void
POA_ProjectManager_PrjMan__fini(PortableServer_Servant servant,
				CORBA_Environment * env)
{
   PortableServer_ServantBase__fini(servant, env);
}
