/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "Prj.h"

#if ( (TC_IMPL_TC_ProjectManager_PrjMan_0 == 'P') \
&& (TC_IMPL_TC_ProjectManager_PrjMan_1 == 'r') \
&& (TC_IMPL_TC_ProjectManager_PrjMan_2 == 'j') \
) && !defined(TC_DEF_TC_ProjectManager_PrjMan)
#define TC_DEF_TC_ProjectManager_PrjMan 1
const struct CORBA_TypeCode_struct TC_ProjectManager_PrjMan_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "PrjMan", "IDL:ProjectManager/PrjMan:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long ProjectManager_PrjMan__classid = 0;
